apiVersion: v1
kind: Pod
metadata:
  name: nginx-dedicated-school
  namespace: dedicated-school-d-melnychenko
  labels: nginx-dedicated-school
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80