apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: dedicated-school-d-melnychenko
spec:
  type: NodePort
  selector:
    app: nginx-dedicated-school
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30007